// This code is automatically generated by Senax and is always overwritten.

#![allow(dead_code)]
#![allow(unused_imports)]
#![allow(unused_variables)]
#![allow(unused_mut)]
#![allow(unreachable_patterns)]

#[rustfmt::skip]
#[allow(clippy::map_identity)]
#[allow(clippy::match_single_binding)]
#[allow(clippy::clone_on_copy)]
#[allow(clippy::nonminimal_bool)]
#[allow(clippy::useless_conversion)]
#[allow(clippy::enum_variant_names)]
#[allow(clippy::collapsible_if)]
#[allow(clippy::assigning_clones)]
#[allow(clippy::too_many_arguments)]
@%- if SEPARATED_BASE_FILES %@
pub mod _base {
@%- for name in mod_names %@
    pub mod _@{ name }@;
@%- endfor %@

@%- for (u, m) in unified_names %@
    pub use _base_filter_@{ db|snake }@_@{ u }@::repositories::@{ group_name|snake|ident }@::_base::_@{ m }@;
@%- endfor %@
}
@%- else %@
pub mod _base {
@{ base_output }@
}
@%- endif %@
@{-"\n"}@