// This code is automatically generated by Senax and is always overwritten.

#![allow(dead_code)]
#![allow(unused_imports)]
#![allow(unused_variables)]
#![allow(unused_mut)]
#![allow(unreachable_patterns)]

use ::anyhow::Result;
use ::fxhash::FxHashMap;
use ::indexmap::IndexMap;
use ::senax_common::{cache::msec::MSec, ShardId};
use ::serde::{Deserialize, Serialize};
use senax_encoder::{Encode, Decode};
use ::std::path::Path;
use ::std::sync::Arc;
use ::std::time::Duration;

use crate::{DbConn, DELAYED_DB_DIR};

@%- if SEPARATED_BASE_FILES %@
@%- for name in mod_names %@
pub mod @{ name|to_var_name }@;
@%- endfor %@
@%- else %@
@{ table_output }@
@%- endif %@

#[rustfmt::skip]
#[allow(clippy::large_enum_variant)]
#[derive(Encode, Decode, Clone, Debug)]
pub enum CacheOp {
@%- for (name, (_, def)) in models %@
    @{ name|to_pascal_name }@(@{ def.mod_name()|to_var_name }@::CacheOp),
@%- endfor %@
}

#[rustfmt::skip]
#[cfg(feature = "seeder")]
#[derive(::schemars::JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct @{ group_name|pascal }@ {
@%- for (name, (_, def)) in models %@
    #[serde(default)]
    @{ name|to_var_name }@: IndexMap<String, @{ def.mod_name()|to_var_name }@::_@{ name|pascal }@Factory>,
@%- endfor %@
}
@{-"\n"}@