// This code is automatically generated by Senax and is always overwritten.
@% if SEPARATED_BASE_FILES %@
@%- for name in mod_names %@
pub mod @{ name|ident }@;
@%- endfor %@
@%- else %@
@{ impl_domain_output }@
@%- endif %@
@{-"\n"}@