// This code is automatically generated by Senax and is always overwritten.

use ::anyhow::Result;
use db::DbConn;

#[allow(unused_imports)]
pub(crate) use base_repository::repositories::@{ group_name|snake|ident }@::_base;
@% for name in mod_names %@
pub mod @{ name|ident }@;
@%- endfor %@

pub async fn seed(seed: &serde_yaml::Value, conns: &mut [DbConn]) -> Result<()> {
    base_repository::repositories::@{ group_name|snake|ident }@::seed(seed, conns).await
}
@{-"\n"}@