// This code is automatically generated by Senax and is always overwritten.

pub mod _base {
@%- for (u, m) in unified_names %@
    pub use _base_repo_@{ db|snake }@_@{ u }@::repositories::@{ group_name|snake|ident }@::_base::_@{ m }@;
@%- endfor %@
}
@% for name in mod_names %@
pub mod @{ name|ident }@;
@%- endfor %@
@{-"\n"}@