// This code is automatically generated by Senax and is always overwritten.
@% for (name, (_, defs)) in groups %@
pub use _db_@{ db|snake }@_@{ name|snake }@::repositories::@{ name|snake|to_var_name }@;
@%- endfor %@

pub fn init() {
    use std::sync::LazyLock;
    static INIT: LazyLock<()> = LazyLock::new(|| {
        @%- for (name, (_, defs)) in groups %@
        _db_@{ db|snake }@_@{ name|snake }@::init();
        @%- endfor %@
        ()
    });
    let _ = *INIT;
}
@{-"\n"}@