// This code is automatically generated by Senax and is always overwritten.

pub use base_repository::repositories::Handler;
@% for (name, (_, defs, _)) in groups %@
pub mod @{ name|snake|ident }@;
@%- endfor %@
@{-"\n"}@