// This code is automatically generated by Senax and is always overwritten.

#![allow(non_snake_case)]
#[rustfmt::skip]
#[allow(clippy::module_inception)]
#[allow(clippy::overly_complex_bool_expr)]
#[allow(clippy::nonminimal_bool)]
#[allow(clippy::useless_conversion)]
#[allow(clippy::only_used_in_recursion)]
#[allow(clippy::map_identity)]
#[allow(clippy::collapsible_if)]
pub mod relations {
@%- for (name, defs) in groups %@
    pub mod @{ name|snake|ident }@;
@%- endfor %@
}
@{-"\n"}@
